<?php
namespace MultiShip\Tests\Carrier;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Configuration;
use MultiShip\Carrier\FedEx;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Carrier\AbstractCarrier
 * @covers MultiShip\Carrier\FedEx
 */
class FedExTest extends BaseTestCase
{

    /**
     * @var FedEx
     */
    protected $object;

    protected function setUp()
    {
        $configuration = new Configuration();

        $this->object = new FedEx( $configuration );
    }

    /**
     * @covers MultiShip\Carrier\FedEx::getSoapHeader
     */
    public function testGetSoapHeader()
    {
        $this->assertNull( $this->object->getSoapHeader() );
    }

    /**
     * @covers MultiShip\Carrier\FedEx::getRateRequest
     */
    public function testGetRateRequest()
    {
        $this->assertInstanceOf( '\MultiShip\Carrier\FedEx\Rate', $this->object->getRateRequest() );
    }

    /**
     * @covers MultiShip\Carrier\FedEx::getSimpleRateRequest
     */
    public function testGetSimpleRateRequest()
    {
        $this->assertInstanceOf( '\MultiShip\Carrier\FedEx\SimpleRate', $this->object->getSimpleRateRequest() );
    }
}

?>