language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install
script:
  - phpunit --configuration tests/phpunit.xml
after_script:
  - php vendor/bin/coveralls -coverage_clover report/logs/clover.xml
