<?php

/*
 * This file is part of the MultiShip package.
 *
 * (c) 2013 Fraser Reed
 *      <fraser.reed@gmail.com>
 *      github.com/fraserreed
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace MultiShip\Tests\Carrier\FedEx;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Configuration;
use MultiShip\Carrier\FedEx;
use MultiShip\Carrier\FedEx\Shipment;

use MultiShip\Address\Address;
use MultiShip\Package\Package;

use MultiShip\Exceptions\MultiShipException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Carrier\FedEx\Shipment
 * @covers MultiShip\Carrier\AbstractCarrier
 * @covers MultiShip\Request\AbstractRequest
 */
class ShipmentTest extends BaseTestCase
{
    /**
     * @var Shipment
     */
    protected $object;

    protected function setUp()
    {
        $configuration = new Configuration();
        $configuration->setUserId( 98100 );
        $configuration->setPassword( 'fedex_password' );
        $configuration->setAccessKey( 'aCC3$$' );
        $configuration->setAccountNumber( 12345678 );
        $configuration->setMeterNumber( 8765432 );

        $this->object = new Shipment();
        $this->object->setConfiguration( $configuration );
        $this->object->setServiceCode( 'FEDEX_GROUND' );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::getServiceCode
     */
    public function testGetServiceCode()
    {
        $this->assertEquals( 'FEDEX_GROUND', $this->object->getServiceCode() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::isShipmentComplete
     */
    public function testIsShipmentCompleteFail()
    {
        $this->assertFalse( $this->object->isShipmentComplete() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::isShipmentComplete
     */
    public function testIsShipmentCompletePass()
    {
        $to = new Address();
        $to->setName( 'Imani Imaginarium' );
        $to->setLine1( '21 ARGONAUT SUITE B' );
        $to->setCity( 'Toronto' );
        $to->setRegion( 'ON' );
        $to->setPostalCode( 'M2N5X7' );
        $to->setCountry( 'CA' );
        $to->setPhoneNumber( 9056883000 );
        $to->setResidentialAddress( true );

        $from = new Address();
        $from->setName( 'Imani Carr' );
        $from->setNumber( 222006 );
        $from->setLine1( 'Southam Rd' );
        $from->setLine2( '4 Case Cour' );
        $from->setLine3( 'Apt 3B' );
        $from->setCity( 'Ottawa' );
        $from->setRegion( 'ON' );
        $from->setPostalCode( 'K1Y1A1' );
        $from->setCountry( 'CA' );
        $from->setPhoneNumber( 9056883000 );

        $this->object->setToAddress( $to );
        $this->object->setFromAddress( $from );

        $package1 = new Package();
        $package1->setHeight( 10 );
        $package1->setWidth( 4 );
        $package1->setLength( 5 );
        $package1->setDimensionUnitOfMeasure( 'in' );
        $package1->setWeight( 1 );
        $package1->setWeightUnitOfMeasure( 'lb' );

        $this->object->addPackage( $package1 );

        $this->object->getRequestBody();

        $this->assertTrue( $this->object->isShipmentComplete() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::getRequestBody
     * @expectedException \MultiShip\Exceptions\MultiShipException
     */
    public function testGetRequestBodyNoFromAddress()
    {
        $this->object->getRequestBody();
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::getRequestBody
     * @expectedException \MultiShip\Exceptions\MultiShipException
     */
    public function testGetRequestBodyNoToAddress()
    {
        $from = new Address();
        $from->setName( 'Imani Carr' );
        $from->setNumber( 222006 );
        $from->setLine1( 'Southam Rd' );
        $from->setLine2( '4 Case Cour' );
        $from->setLine3( 'Apt 3B' );
        $from->setCity( 'Timonium' );
        $from->setRegion( 'MD' );
        $from->setPostalCode( 21093 );
        $from->setCountry( 'US' );

        $this->object->setFromAddress( $from );

        $this->object->getRequestBody();
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::getRequestBody
     * @expectedException \MultiShip\Exceptions\MultiShipException
     */
    public function testGetRequestBodyNoPackages()
    {
        $to = new Address();
        $to->setName( 'Imani Imaginarium' );
        $to->setLine1( '21 ARGONAUT SUITE B' );
        $to->setCity( 'ALISO VIEJO' );
        $to->setRegion( 'CA' );
        $to->setPostalCode( 92656 );
        $to->setCountry( 'US' );

        $from = new Address();
        $from->setName( 'Imani Carr' );
        $from->setNumber( 222006 );
        $from->setLine1( 'Southam Rd' );
        $from->setLine2( '4 Case Cour' );
        $from->setLine3( 'Apt 3B' );
        $from->setCity( 'Timonium' );
        $from->setRegion( 'MD' );
        $from->setPostalCode( 21093 );
        $from->setCountry( 'US' );

        $this->object->setToAddress( $to );
        $this->object->setFromAddress( $from );

        $this->object->getRequestBody();
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::getRequestBody
     */
    public function testGetRequestBody()
    {
        $to = new Address();
        $to->setName( 'Imani Imaginarium' );
        $to->setLine1( '21 ARGONAUT SUITE B' );
        $to->setCity( 'Toronto' );
        $to->setRegion( 'ON' );
        $to->setPostalCode( 'M2N5X7' );
        $to->setCountry( 'CA' );
        $to->setPhoneNumber( 9056883000 );
        $to->setResidentialAddress( true );

        $from = new Address();
        $from->setName( 'Imani Carr' );
        $from->setNumber( 222006 );
        $from->setLine1( 'Southam Rd' );
        $from->setLine2( '4 Case Cour' );
        $from->setLine3( 'Apt 3B' );
        $from->setCity( 'Ottawa' );
        $from->setRegion( 'ON' );
        $from->setPostalCode( 'K1Y1A1' );
        $from->setCountry( 'CA' );
        $from->setPhoneNumber( 9056883000 );

        $this->object->setToAddress( $to );
        $this->object->setFromAddress( $from );

        $package1 = new Package();
        $package1->setHeight( 10 );
        $package1->setWidth( 4 );
        $package1->setLength( 5 );
        $package1->setDimensionUnitOfMeasure( 'in' );
        $package1->setWeight( 1 );
        $package1->setWeightUnitOfMeasure( 'lb' );

        $this->object->addPackage( $package1 );

        $this->object->setServiceCode( 'FEDEX_GROUND' );

        $body = $this->object->getRequestBody();

        $data = json_decode( $this->getFixture( 'FedEx/ShipmentRequestBody.json' ), true );

        //timestamp is dynamic, so set it as a match
        $data[ 'RequestedShipment' ][ 'ShipTimestamp' ] = $body[ 'RequestedShipment' ][ 'ShipTimestamp' ];

        $this->assertEquals( $data, $body );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::parseResponse
     */
    public function testParseResponse()
    {
        $data     = $this->getFixture( 'FedEx/ShipmentResponse.json' );
        $response = json_decode( $data, false );

        $actual = $this->object->parseResponse( $response );

        /** @var $shipment \MultiShip\Response\Elements\ShipmentPackage */
        foreach( $actual->getShipmentPackages() as $shipment )
        {
            $this->assertContains( $shipment->getTotal()->getValue(), array( 59.03 ) );
            $this->assertContains( $shipment->getTrackingNumber(), array( '794821390890' ) );
        }

        $this->assertEquals( 'SUCCESS', $actual->getStatusCode() );
        $this->assertEquals( 'Success', $actual->getStatusDescription() );
        $this->assertEquals( 1, $actual->getCount() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::parseResponse
     */
    public function testParseResponseMultiplePackages()
    {
        $data     = $this->getFixture( 'FedEx/ShipmentResponseMultipleMasterPackage.json' );
        $response = json_decode( $data, false );

        //first pass master package
        $this->object->parseResponse( $response );

        $data     = $this->getFixture( 'FedEx/ShipmentResponseMultipleChildPackage.json' );
        $response = json_decode( $data, false );

        //second pass child package
        $actual = $this->object->parseResponse( $response );

        //validate master tracking number
        $this->assertEquals( '794828000431', $actual->getMasterTrackingNumber() );

        /** @var $shipment \MultiShip\Response\Elements\ShipmentPackage */
        foreach( $actual->getShipmentPackages() as $shipment )
        {
            $this->assertContains( $shipment->getTotal()->getValue(), array( 14.98 ) );
            $this->assertContains( $shipment->getBillingPackage()->getWeight(), array( 1.0, 2.0 ) );
            $this->assertContains( $shipment->getTrackingNumber(), array( '794828000431', '794828000442' ) );
        }

        $this->assertEquals( 3.0, $actual->getBillingPackage()->getWeight() );

        $this->assertEquals( 'SUCCESS', $actual->getStatusCode() );
        $this->assertEquals( 'Success', $actual->getStatusDescription() );
        $this->assertEquals( 2, $actual->getCount() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::parseResponse
     */
    public function testParseResponseNet()
    {
        $data     = $this->getFixture( 'FedEx/ShipmentResponseNet.json' );
        $response = json_decode( $data, false );

        $actual = $this->object->parseResponse( $response );

        /** @var $shipment \MultiShip\Response\Elements\ShipmentPackage */
        foreach( $actual->getShipmentPackages() as $shipment )
        {
            $this->assertContains( $shipment->getTotal()->getValue(), array( 59.03 ) );
            $this->assertContains( $shipment->getTrackingNumber(), array( '794821390890' ) );
        }

        $this->assertEquals( 'SUCCESS', $actual->getStatusCode() );
        $this->assertEquals( 'Success', $actual->getStatusDescription() );
        $this->assertEquals( 1, $actual->getCount() );
    }

    /**
     * @covers \MultiShip\Carrier\FedEx\Shipment::parseResponse
     */
    public function testParseResponseEmpty()
    {
        $data     = $this->getFixture( 'FedEx/ShipmentResponseEmpty.json' );
        $response = json_decode( $data, false );

        $actual = $this->object->parseResponse( $response );

        $this->assertEmpty( $actual->getShipmentPackages() );

        $this->assertEquals( 'SUCCESS', $actual->getStatusCode() );
        $this->assertEquals( 'Success', $actual->getStatusDescription() );
        $this->assertEquals( 0, $actual->getCount() );
    }
}

?>