<?php

/*
 * This file is part of the MultiShip package.
 *
 * (c) 2013 Fraser Reed
 *      <fraser.reed@gmail.com>
 *      github.com/fraserreed
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace MultiShip\Tests\Carrier;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Charge\FreightCharge;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Charge\AbstractCharge
 * @covers MultiShip\Charge\FreightCharge
 */
class FreightChargeTest extends BaseTestCase
{

    /**
     * @var FreightCharge
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new FreightCharge();
    }

    /**
     * @covers MultiShip\Charge\FreightCharge::getChargeType
     */
    public function testGetChargeType()
    {
        $this->assertEquals( 'Freight', $this->object->getChargeType() );
    }
}

?>