<?php
namespace MultiShip\Tests\Carrier;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Charge\FreightDiscountCharge;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Charge\AbstractCharge
 * @covers MultiShip\Charge\FreightDiscountCharge
 */
class FreightDiscountChargeTest extends BaseTestCase
{

    /**
     * @var FreightDiscountCharge
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new FreightDiscountCharge();
    }

    /**
     * @covers MultiShip\Charge\FreightDiscountCharge::getChargeType
     */
    public function testGetChargeType()
    {
        $this->assertEquals( 'FreightDiscount', $this->object->getChargeType() );
    }
}

?>