<?php
namespace MultiShip\Tests\Carrier;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Charge\TaxCharge;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Charge\AbstractCharge
 * @covers MultiShip\Charge\TaxCharge
 */
class TaxChargeTest extends BaseTestCase
{

    /**
     * @var TaxCharge
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new TaxCharge();
    }

    /**
     * @covers MultiShip\Charge\TaxCharge::getChargeType
     */
    public function testGetChargeType()
    {
        $this->assertEquals( 'Tax', $this->object->getChargeType() );
    }
}

?>