<?php
namespace MultiShip\Tests\Carrier;


use MultiShip\Tests\BaseTestCase;

use MultiShip\Charge\TransportationCharge;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-15 at 10:22:52.
 *
 * @covers MultiShip\Charge\AbstractCharge
 * @covers MultiShip\Charge\TransportationCharge
 */
class TransportationChargeTest extends BaseTestCase
{

    /**
     * @var TransportationCharge
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new TransportationCharge();
    }

    /**
     * @covers MultiShip\Charge\TransportationCharge::getChargeType
     */
    public function testGetChargeType()
    {
        $this->assertEquals( 'Transportation', $this->object->getChargeType() );
    }
}

?>