<?php

/*
 * This file is part of the MultiShip package.
 *
 * (c) 2013 Fraser Reed
 *      <fraser.reed@gmail.com>
 *      github.com/fraserreed
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace MultiShip\Tests;


use MultiShip\Exceptions\MultiShipException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-03 at 10:33:52.
 */
abstract class BaseTestCase extends \PHPUnit_Framework_TestCase
{

    /**
     * Fetch a testing fixture
     *
     * @param      $file
     * @param bool $returnContent
     *
     * @throws \MultiShip\Exceptions\MultiShipException
     *
     * @return string
     */
    public function getFixture( $file, $returnContent = true )
    {
        $path = dirname( dirname( __FILE__ ) ) . '/Fixtures/' . $file;

        if( file_exists( $path ) )
        {
            if( $returnContent )
                return file_get_contents( $path );
            else
                return $path;
        }

        throw new MultiShipException( 'Fixture path does not exist: ' . $path );
    }
}
